.catalog:
  name: "Redis Replicas"
  version: "v1"
  description: "Redis: deploy redis Replicas, pressing button plus into service slave to scaling this Replicas redis"
  questions:
    - variable: "slave_can_write"
      label: "Slave can write in cluster"
      description: "not recomment using value: true"
      required: true
      default: false
      type: "boolean"
    - variable: "master_redis_config"
      description: |
        Cấu hình của master
      label: "Config Master"
      required: true
      type: "multiline"
      default: |
        port 6379
        dir /redis-data
        appendonly yes
    - variable: "slave_redis_config"
      description: |
        Cấu hình của slave
      label: "Config Slave"
      required: true
      type: "multiline"
      default: |
        port 6379
        dir /redis-data
        slaveof master 6379
        appendonly yes
master:
  metadata:
    redis:
      master: |
        ${master_redis_config}
slave:
  metadata:
    redis:
      slave: |
        ${slave_redis_config}
