.catalog:
  name: Zookeeper
  version: 3.4.6-rancher1
  description: |
    (Experimental) Apache Zookeeper cluster.
  minimum_rancher_version: v0.56.0
  maintainer: "Raul Sanchez <rawmind@gmail.com>"
  uuid: zk-0
  questions:
    - variable: "zk_scale"
      description: "Number of zk nodes. Note: Recommended an odd number"
      label: "Zk Nodes:"
      required: true
      default: 3
      type: "int"
    - variable: "zk_mem"
      description: "Amount of memory to config zk."
      label: "Zk Memory (mb):"
      required: true
      default: 512
      type: "string"
    - variable: "zk_interval"
      description: "Interval to poll/apply configuration changes. 0 to disable, reconfiguration will be done when you restart zk nodes"
      label: "Zk Interval (s):"
      required: true
      default: 60
      type: "int"
    - variable: "host_label"
      description: "Hosts with label to deploy the kafka cluster"
      label: "Host label:"
      required: true
      default: "stack=devops"
      type: "string"
zk:
  scale: ${zk_scale}
  health_check:
    port: 2181
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
