.catalog:
  name: Atlassian Bitbucket Server
  version: 4.5.1
  description: Atlassian Bitbucket Server source code repository server
  uuid: atlassian-bitbucket-4-5-1

Bitbucket:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    recreate_on_quorum_strategy_config:
      quorum: 1
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreateOnQuorum
    response_timeout: 2000
    request_line: GET "/" "HTTP/1.0"
    healthy_threshold: 2