.catalog:
  name: core-leankit-api
  version: 3.8.0-2
  description: "Leankit Internal Node App: core-leankit-api"
  uuid: core-leankit-api-3.8.0-2
  questions:
    - variable: auth_salt
      label: API Token Salt
      type: password
      required: true

core-leankit-api:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 2
    healthy_threshold: 2
    response_timeout: 1000

core-leankit-api-app:
  scale: 1
  health_check:
    port: 8008
    interval: 2000
    unhealthy_threshold: 2
    request_line: GET /node/api/status HTTP/1.1
    healthy_threshold: 2
    response_timeout: 1000
