owncloud-entry:
  ports:
  - 443:80
  labels:
    io.rancher.loadbalancer.ssl.ports: '443'
    io.rancher.loadbalancer.target.owncloud: '80'
    io.rancher.scheduler.affinity:host_label: owncloud=true
  image: rancher/load-balancer-service
  links:
    - owncloud:owncloud

owncloud:
  image: owncloud
  expose:
    - "80"
  volumes:
    - /srv/owncloud:/var/www/html
  links:
    - owncloud-db:db
  labels:
    io.rancher.scheduler.affinity:host_label: owncloud=true

owncloud-db:
  image: rancher/external-service
