app:
  image: baselibrary/nexus:3.0
  environment:
    - VIRTUAL_HOST=${vhost}
    - VIRTUAL_PORT=8081
  labels:
    io.rancher.sidekicks: app-data
  ports:
    - "5000-5100:5000-5100"

app-data:
  image: busybox:1.24
  volumes_from:
    - app
  command: ["echo", "app data container"]
  labels:
    io.rancher.container.start_once: true