.catalog:
  name: "Nexus"
  version: "3"
  description: "Sonatype Nexus Repository Manager"
  uuid: nexus-3-0sdaf7g6-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: "vhost"
      description: "Virtual Host"
      label: "Virtual Host:"
      required: true
      default: "developer-customer.docker1.brandung.dev"
      type: "string"