redis:
  image: rancher/load-balancer-service
  ports:
    - 6379:6379/tcp
  stdin_open: true
  tty: true
  links:
    - master:master
  labels:
    io.leankit.service.port: 6379/tcp

master:
  image: redis:3.0.7
  expose:
    - 6379/tcp
  stdin_open: true
  tty: true
  command:
    - redis-server
    - --save
    - ''
    - --maxmemory
    - 1gb
  labels:
    io.rancher.container.pull_image: always
