scm-data:
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: name=node01
  entrypoint:
  - /bin/true
  image: fabn/scm-manager
  volumes:
  - /data
scm-server:
  ports:
  - 9000:8080/tcp
  labels:
    io.rancher.sidekicks: scm-data
    io.rancher.scheduler.affinity:host_label: name=node01
  image: fabn/scm-manager
  volumes_from:
  - scm-data
