.catalog:
  name: "SCM Manager"
  version: "1.46.1"
  description: "SCM Manager - Hosts Git, SVN and HG repositories"
scm-data:
  scale: 1
scm-server:
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    strategy: none
    request_line: HEAD / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
