mysql:
  image: vibioh/mysql
  ports:
  - ${MYSQL_PORT}:3306/tcp
  labels:
    traefik.enable: false
  environment:
  - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  - MYSQL_DATABASE=${MYSQL_DATABASE}
  - MYSQL_USER=${MYSQL_USER}
  - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  log_opt:
    max-size: '50m'
  restart: 'no'
  read_only: true
  cpu_shares: 512
  mem_limit: 268435456