kafka:
  tty: true
  image: rawmind/rancher-kafka:0.9.0
  volumes:
  - /opt/kafka/data
  environment:
  - JVMFLAGS=-Xmx${kafka_mem}m -Xms${kafka_mem}m
  - CONFD_INTERVAL=${kafka_interval}
  - ZK_SERVICE=${zk_link}
  external_links:
  - ${zk_link}:zk
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_label}
