.catalog:
  name: Kafka
  version: 0.9.0-rancher1
  description: |
    (Experimental) Apache Kafka cluster.
  minimum_rancher_version: v0.56.0
  maintainer: "Raul Sanchez <rawmind@gmail.com>"
  uuid: kafka-0
  questions:
    - variable: "kafka_scale"
      description: "Number of brokers nodes. Note: Recommended an odd number"
      label: "Broker Nodes:"
      required: true
      default: 3
      type: "int"
    - variable: "kafka_mem"
      description: "Amount of memory to config brokers."
      label: "Broker Memory (mb):"
      required: true
      default: 1024
      type: "string"
    - variable: "kafka_interval"
      description: "Interval to poll/apply configuration changes. 0 to disable"
      label: "Broker Interval (s):"
      required: true
      default: 60
      type: "int"
    - variable: "host_label"
      description: "Hosts with label to deploy the kafka cluster"
      label: "Host label:"
      required: true
      default: "stack=devops"
      type: "string"
    - variable: "zk_link"
      description: |
        Choose the Zookeeper service to use.
        It's really recommended a dedicated zookeeper service just for Kafka.
      label: "Zookeeper stack/service"
      default: "kafka-zk/zk"
      required: true
      type: "service"
kafka:
  scale: ${kafka_scale}
  health_check:
    port: 9092
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
