zk:
  restart: always
  image: rawmind/rancher-zk:3.4.6-1
  volumes:
  - /opt/zk/data
  environment:
  - JVMFLAGS=-Xmx${zk_mem}m -Xms${zk_mem}m
  - CONFD_INTERVAL=${zk_interval}
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_label}
    io.rancher.container.hostname_override: container_name

kafka:
  restart: always
  image: rawmind/rancher-kafka:0.9.0
  volumes:
  - /opt/kafka/data
  environment:
  - JVMFLAGS=-Xmx${kafka_mem}m -Xms${kafka_mem}m
  - CONFD_INTERVAL=${kafka_interval}
  - ZK_SERVICE=devops/zk
  links:
  - zk
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_label}
    io.rancher.container.hostname_override: container_name

influxdb:
  restart: always
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_label}
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
  image: autoshift/influxdb-docker:0.12
  environment:
    - ADMIN_USER=root
    - INFLUXDB_INIT_PWD=root
    - PRE_CREATE_DB=telegraf
  mem_limit: 1024000000
  memswap_limit: 1024000000
  cpu_shares: 512
