.catalog:
  name: Sentry
  version: 8.10.0
  description: Sentry is a realtime event logging and aggregation platform

  questions:
    - variable: "sentry_secret_key"
      type: "password"
      required: true
      label: "SENTRY_SECRET_KEY"
      description: "A secret key used for cryptographic functions within Sentry. see https://hub.docker.com/_/sentry/ for more info"

    - variable: "sentry_public_port"
      type: "int"
      required: false
      label: "Sentry public port"
      description: "Port that Sentry will listen on. Alternatively you could point a load balancer to the port 9000 of this container"

    - variable: "sentry_inital_user_email"
      type: "string"
      required: true
      label: "SENTRY_INITAL_USER_EMAIL"
      description: "The initial superuser email"

    - variable: "sentry_inital_user_password"
      type: "password"
      required: true
      label: "SENTRY_INITAL_USER_PASSWORD"
      description: "The initial superuser password. Please use a simple intial password and change it afterwards in the Sentry interface"

    - variable: "sentry_server_email"
      type: "string"
      required: false
      label: "SENTRY_SERVER_EMAIL"
      description: "The email in the FROM section. see https://hub.docker.com/_/sentry/ for more info"

    - variable: "sentry_email_host"
      type: "string"
      required: false
      label: "SENTRY_EMAIL_HOST"
      description: "The smtp server address. see https://hub.docker.com/_/sentry/ for more info"

    - variable: "sentry_email_user"
      type: "string"
      required: false
      label: "SENTRY_EMAIL_USER"
      description: "The username for the email account. see https://hub.docker.com/_/sentry/ for more info"

    - variable: "sentry_email_password"
      type: "password"
      required: false
      label: "SENTRY_EMAIL_PASSWORD"
      description: "The password for the email account. see https://hub.docker.com/_/sentry/ for more info"

    - variable: "sentry_email_use_tls"
      type: "boolean"
      required: false
      label: "SENTRY_EMAIL_USE_TLS"
      description: "Set if email connection use TLS. see https://hub.docker.com/_/sentry/ for more info"

    - variable: "sentry_email_port"
      type: "int"
      required: false
      label: "SENTRY_EMAIL_PORT"
      description: "Port of the smtp server. see https://hub.docker.com/_/sentry/ for more info"

    - variable: "gitlab_app_id"
      type: "string"
      required: false
      label: "GITLAB_APP_ID"
      description: "The gitlab APP ID for the oauth connecton to gitlab server"

    - variable: "gitlab_app_secret"
      type: "string"
      required: false
      label: "GITLAB_APP_SECRET"
      description: "The gitlab APP Secret for the oauth connecton to gitlab server"

    - variable: "gitlab_base_domain"
      type: "string"
      required: false
      label: "GITLAB_BASE_DOMAIN"
      description: "gitlab host url"
      default: "git.example.com"

    - variable: "gitlab_api_version"
      type: "int"
      required: false
      label: "GITLAB_API_VERSION"
      description: "gitlab API version"
      default: 3

    - variable: "gitlab_http_scheme"
      type: "string"
      required: false
      label: "GITLAB_HTTP_SCHEME"
      description: "gitlab host url scheme : http or https only"
      default: "https"
