.catalog:
  name: "Sentry"
  version: "v0.1.0"
  questions:
    - variable: "SENTRY_SECRET_KEY"
      label: "Secret key"
      description: "Your unique secret key."
      type: "password"
      required: true
    - variable: "PUBLIC_PORT"
      label: "Public port"
      description: "Public port to expose sentry."
      type: "int"
      default: 9000
      required: true

sentry-redis:
  scale: 1

sentry-postgres:
  scale: 1

sentry:
  scale: 1

sentry-celery-beat:
  scale: 1

sentry-celery:
  scale: 1

sentry-lb:
  scale: 1
