version: '2'
services:
    jenkins-primary:
      image: "jenkins:2.46.2-alpine"
      ports:
        - "8080"
      labels:
        io.rancher.sidekicks: jenkins-plugins
        io.rancher.container.hostname_override: container_name
      volumes_from:
        - jenkins-plugins
      volumes:
        - jenkins-storage:/var/jenkins_home
      entrypoint: /usr/share/jenkins/rancher/jenkins.sh
    jenkins-plugins:
      image: rancher/jenkins-plugins:v0.1.1
volumes:
  jenkins-storage:
    driver: rancher-nfs
    external: true