traefik:
  image: emilevauge/traefik:latest
  ports:
  - ${LISTEN_PORT}:80/tcp
  labels:
    traefik.port: '${WEB_PORT}'
    traefik.frontend.rule: 'Host'
    traefik.frontend.value: 'traefik.${DOMAIN}'
    traefik.frontend.passHostHeader: 'true'
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - ${TRAEFIK_DIR}/traefik.toml:/traefik.toml
  read_only: true
  log_opt:
    max-size: '50m'
  restart: 'no'
  cpu_shares: 256
  mem_limit: 134217728