Redis:
  image: redis

Mailserver:
  tty: true
  image: ubuntu:14.04.3
  stdin_open: true

Discourse:
  environment:
    DISCOURSE_DB_PASSWORD: ${DISCOURSE_DB_PASSWORD}
    DISCOURSE_SMTP_ADDRESS: mailserver
    DISCOURSE_DEVELOPER_EMAILS: ${DISCOURSE_DEVELOPER_EMAILS}
    DISCOURSE_SERVE_STATIC_ASSETS: 'true'
  image: envygeeks/discourse
  links:
  - Mailserver:mailserver
  - PostgresSQL:postgresql
  - Redis:redis
  volumes:
  - /data/${ORGANIZATION}/Discourse/volumes/opt/discourse/public/uploads:/opt/discourse/public/uploads
PostgresSQL:
  environment:
    POSTGRES_PASSWORD: discourse
    INIT_USER: discourse:login:${DISCOURSE_DB_PASSWORD}
    INIT_DB: discourse::hstore,pg_trgm
    INIT_DEBUG: 'true'
  image: steigr/postgres
  volumes:
  - /data/${ORGANIZATION}/PostgresSQL/volumes/var/lib/postgresql/data:/var/lib/postgresql/data
