.catalog:
  name: "Kibana"
  version: "4.3.1-mgolly1"
  description: "Kibana: Explore & Visualize Your Data"
  uuid: kibana-4
  questions:
    - variable: "elasticsearch_source"
      description: "Link to elasticsearch service or stack/service"
      label: "Elasticsearch source"
      type: "service"
      required: true
      default: "es/elasticsearch-clients"
nginx-proxy:
  metadata:
    nginx:
      conf:
        servername: "kibana"
        upstream_port: 5601 
