.catalog:
  name: JetBrains Upsource
  version: 3.0.4237
  description: JetBrains Upsource code review application
  uuid: jetbrains-stack-1

Upsource:
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    recreate_on_quorum_strategy_config:
      quorum: 1
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreateOnQuorum
    response_timeout: 2000
    request_line: GET "/" "HTTP/1.0"
    healthy_threshold: 2
