.catalog:
  name: "JetBrains Hub"
  version: "1.0.809"
  description: "JetBrains Hub"
  uuid: jetbrains-hub-1

Hub:
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    recreate_on_quorum_strategy_config:
      quorum: 1
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreateOnQuorum
    response_timeout: 2000
    request_line: GET "/" "HTTP/1.0"
    healthy_threshold: 2