elasticsearch:
  image: elasticsearch:2

logstash:
  image: nexus.docker1.brandung.dev:5000/logstash
  command: -f /etc/logstash.conf
  environment:
    - LOGSPOUT=ignore
  links:
    - elasticsearch

kibana:
  image: kibana:4
  environment:
    - VIRTUAL_HOST=${vhost}
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  links:
    - elasticsearch

logspout:
  image: gliderlabs/logspout:v3
  environment:
    - DEBUG=true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: syslog://logstash:5000
  links:
    - logstash