.catalog:
  name: PHPPGAdmin
  description: PostgreSQL PHP Administration Tool
  version: 5.2-dev
  uuid: phppgadmin-phppgadmin-0
  questions: 
  - variable: "DATABASE_CONTAINER"
    label: "Database Server Container"
    description: "Database Server Container"
    type: "string"
    default: Default/postgres
  - variable: "PHPPGADMIN_PATH"
    label: "Webapplication path"
    description: "Webapplication path"
    type: "string"
    default: /

PHPPGAdmin:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    recreate_on_quorum_strategy_config:
      quorum: 1
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreateOnQuorum
    response_timeout: 2000
    request_line: GET "${PHPPGADMIN_PATH}" "HTTP/1.0"
    healthy_threshold: 2
