.catalog:
  name: Kong
  version: v0.8.3
  description: |
    Kong API Gateway
  minimum_rancher_version: v1.0.0
  uuid: kong-0
kong:
  retain_ip: true
  health_check:
    port: 8001
    interval: 5000
    unhealthy_threshold: 3
    request_line: 'GET /# HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 5000
