migap-galaxy-ge:
  image: emihat/migal-ge
  stdin_open: true
  tty: true
  privileged: true
  ports:
   - "80:8082"
  labels:
    "Version": "v0.0.5"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - /usr/bin/docker:/bin/docker
   - /var/lib/gridengine:/var/lib/gridengine
   - /mnt/data:/data
   - /tmp/files:/tmp/files
   - /mnt/galaxy_test:/mnt/galaxy_test
  extra_hosts:
   - "og05-medium03:192.168.1.53"

