.catalog:
  name: leankit-tableau
  version: 0.0.0-0
  description: "Leankit Internal Node App: leankit-tableau"
  uuid: leankit-tableau-0.0.0-0

leankit-tableau:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 2
    healthy_threshold: 2
    response_timeout: 1000

leankit-tableau-app:
  scale: 1
  health_check:
    port: 8048
    interval: 2000
    unhealthy_threshold: 2
    request_line: GET /_status HTTP/1.1
    healthy_threshold: 2
    response_timeout: 1000
