marathon:
  image: helk/marathon:${VERSION}
  environment:
    MESOS_SERVICE: ${MESOS_SERVICE}
    ZK_SERVICE: ${ZK_SERVICE}
    MARATHON_HTTP_PORT: ${MARATHON_HTTP_PORT}
  ports:
  - "${MARATHON_HTTP_PORT}:${MARATHON_HTTP_PORT}"
