.catalog:
  name: Marathon
  version: v1
  description: |
    Container orchestration platform for Mesos and DCOS
  questions:
  - variable: VERSION
    label: Marathon Version
    description: Select the version of Marathon to run.
    required: true
    type: enum
    default: 0.11.02-ubuntu-15.04
    options:
    - 0.11.02-ubuntu-15.04
    - 0.11.02-centos-7
  - variable: ZK_SERVICE
    description: Choose the Zookeeper service to use.
    label: Zookeeper Service
    required: true
    type: service
  # a stack type would be nice
  - variable: MESOS_SERVICE
    description: Choose the Mesos stack to use.
    label: Mesos Stack
    required: true
    type: service
  - variable: MARATHON_HTTP_PORT
    description: Port to expose Marathon on.
    label: Marathon Port
    required: true
    type: int
    default: 8080
marathon:
  scale: 1
  health_check:
    port: ${MARATHON_HTTP_PORT}
    interval: 3000
    unhealthy_threshold: 2
    healthy_threshold: 2
    request_line: '/'
    response_timeout: 2000
