proxy:
  container_name: proxy
  restart: always
  image: accenture/adop-nginx:0.1.0
  net: ${CUSTOM_NETWORK_NAME}
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - nginx_config:/etc/nginx
    - nginx_releasenote:/usr/share/nginx/html
  environment:
    - "constraint:tier==public"
    - "LDAP_SERVER=ldap:389"
    - "LDAP_USERNAME=cn=admin,${LDAP_FULL_DOMAIN}"
    - "LDAP_PASSWORD=${LDAP_PWD}"
    - "LDAP_USER_BASE_DN=ou=people,${LDAP_FULL_DOMAIN}"
    - "LDAP_GROUP_ATTRIBUTE=member"
    - "LDAP_USER_ID_ATTRIBUTE=cn"
    - "LDAP_USER_OBJECT_CLASS=inetOrgPerson"
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: proxy

ldap:
  container_name: ldap
  restart: always
  image: accenture/adop-ldap:0.1.0
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "389"
  volumes:
    - ldap_db:/var/lib/ldap
    - ldap_static:/etc/ldap
  environment:
    SLAPD_PASSWORD: ${LDAP_PWD}
    SLAPD_DOMAIN: ${LDAP_DOMAIN}
    SLAPD_FULL_DOMAIN: ${LDAP_FULL_DOMAIN}
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: ldap

jenkins:
  container_name: jenkins
  restart: always
  image: accenture/adop-jenkins:0.1.0
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "8080"
    - "50000"
  privileged: true
  user: root
  volumes:
    - jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    JENKINS_OPTS: "--prefix=/jenkins"
    ROOT_URL: "http://${TARGET_HOST}/jenkins/"
    LDAP_SERVER: "ldap:389"
    LDAP_ROOTDN: "${LDAP_FULL_DOMAIN}"
    LDAP_USER_SEARCH_BASE: "ou=people"
    LDAP_USER_SEARCH: "uid={0}"
    LDAP_GROUP_SEARCH_BASE: "ou=groups"
    LDAP_GROUP_SEARCH_FILTER: ""
    LDAP_GROUP_MEMBERSHIP_FILTER: ""
    LDAP_MANAGER_DN: "cn=admin,${LDAP_FULL_DOMAIN}"
    LDAP_MANAGER_PASSWORD: ${LDAP_PWD}
    LDAP_INHIBIT_INFER_ROOTDN: "false"
    LDAP_DISABLE_MAIL_ADDRESS_RESOLVER: "false"
    LDAP_DISPLAY_NAME_ATTRIBUTE_NAME: "displayName"
    LDAP_MAIL_ADDRESS_ATTRIBUTE_NAME: "mail"
    GERRIT_HOST_NAME: "gerrit"
    GERRIT_FRONT_END_URL: "http://gerrit:8080/gerrit"
    SONAR_SERVER_URL: "http://sonar:9000/sonar/"
    SONAR_ACCOUNT_LOGIN: ${SONAR_ACCOUNT_LOGIN}
    SONAR_ACCOUNT_PASSWORD: ${SONAR_ACCOUNT_PASSWORD}
    SONAR_DB_URL: "jdbc:mysql://sonar-mysql:3306/sonar?useUnicode=true&amp;characterEncoding=utf8"
    SONAR_DB_LOGIN: ${SONAR_DB_LOGIN}
    SONAR_DB_PASSWORD: ${SONAR_DB_PASSWORD}
    SONAR_PLUGIN_VERSION: ""
    SONAR_ADDITIONAL_PROPS: ""
    SONAR_RUNNER_VERSION: "2.4"
    ANT_VERSION: "1.9.4"
    MAVEN_VERSION: "3.0.5"
    NODEJS_VERSION: "0.12.2"
    NODEJS_GLOBAL_PACKAGES: "grunt-cli@~0.1.13 bower@~1.3.12 plato@~1.2.1"
    NODEJS_PACKAGES_REFRESH_HOURS: "72"
    GIT_GLOBAL_CONFIG_NAME: "ADOP Jenkins"
    GIT_GLOBAL_CONFIG_EMAIL: "jenkins@${LDAP_DOMAIN}"
    DOCKER_TLS_VERIFY: ${DOCKER_TLS_VERIFY}
    DOCKER_HOST: ${DOCKER_HOST}
    DOCKER_CLIENT_CERT_PATH: ${DOCKER_CLIENT_CERT_PATH}
    DOCKER_NETWORK_NAME: ${CUSTOM_NETWORK_NAME}
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: jenkins

jenkins-slave:
  container_name: jenkins-slave
  restart: always
  image: accenture/adop-jenkins-slave:0.1.3
  net: ${CUSTOM_NETWORK_NAME}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  privileged: true
  environment:
    SLAVE_LABELS: "aws ldap java8 docker"
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: jenkins-slave

sensu-uchiwa:
  container_name: sensu-uchiwa
  restart: always
  image: sstarcher/uchiwa
  net: ${CUSTOM_NETWORK_NAME}
  environment:
    SENSU_HOSTNAME: sensu-api
  expose:
    - "3000"
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: sensu-uchiwa

sensu-api:
  container_name: sensu-api
  restart: always
  image: accenture/adop-sensu:0.1.0
  net: ${CUSTOM_NETWORK_NAME}
  command: api
  expose:
    - "4567"
  volumes:
    - sensu_api_conf:/etc/sensu/conf.d
  environment:
    RABBITMQ_HOST: sensu-rabbitmq
    REDIS_HOST: sensu-redis
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: sensu-api

sensu-server:
  container_name: sensu-server
  restart: always
  image: accenture/adop-sensu:0.1.0
  net: ${CUSTOM_NETWORK_NAME}
  command: server
  volumes:
    - sensu_server_conf:/etc/sensu/conf.d
  environment:
    CLIENT_NAME: core
    API_HOST: sensu-api
    RABBITMQ_HOST: sensu-rabbitmq
    REDIS_HOST: sensu-redis
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: sensu-server

sensu-client:
  container_name: sensu-client
  restart: always
  image: accenture/adop-sensu:0.1.0
  net: ${CUSTOM_NETWORK_NAME}
  command: client
  volumes:
    - sensu_client_conf:/etc/sensu/conf.d
  environment:
    CLIENT_NAME: core
    RABBITMQ_HOST: sensu-rabbitmq
    JENKINS_PREFIX: jenkins
    CLIENT_SUBSCRIPTIONS: "proxy,gerrit,jenkins,nexus,sonarqube,sensu,kibana"
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: sensu-client

sensu-rabbitmq:
  container_name: sensu-rabbitmq
  restart: always
  image: rabbitmq:3.5.7-management
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "5672"
    - "5671"
    - "15672"
    - "15671"
  volumes:
    - sensu_rabbitmq_data:/var/lib/rabbitmq
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: sensu-rabbitmq

sensu-redis:
  container_name: sensu-redis
  restart: always
  image: redis:3.0.7
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "6379"
  volumes:
    - sensu_redis_data:/data
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: sensu-redis

sonar-mysql:
  container_name: sonar-mysql
  restart: always
  image: mysql:5.6.25
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "3306"
  volumes:
    - sonar_mysql_data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: "sonar"
    MYSQL_USER: ${SONAR_MYSQL_USER}
    MYSQL_PASSWORD: ${SONAR_MYSQL_PASSWORD}
    MYSQL_DATABASE: ${SONAR_MYSQL_DATABASE}
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: sonar-mysql

sonar:
  container_name: sonar
  restart: always
  image: accenture/adop-sonar:0.1.0
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "9000"
  volumes:
    - sonar_data:/opt/sonarqube/data
    - sonar_extensions:/opt/sonarqube/extensions
    - sonar_logs:/opt/sonarqube/logs
  environment:
    - "affinity:container==sonar-mysql"
    - "LDAP_URL=ldap://ldap:389"
    - "LDAP_BIND_DN=cn=admin,${LDAP_FULL_DOMAIN}"
    - "LDAP_BIND_PASSWORD=${LDAP_PWD}"
    - "LDAP_USER_BASE_DN=ou=people,${LDAP_FULL_DOMAIN}"
    - "LDAP_USER_REQUEST=(&(objectClass=inetOrgPerson)(uid={login}))"
    - "LDAP_USER_REAL_NAME_ATTRIBUTE=displayName"
    - "LDAP_USER_EMAIL_ATTRIBUTE=mail"
    - "LDAP_GROUP_BASE_DN=ou=groups,${LDAP_FULL_DOMAIN}"
    - "LDAP_GROUP_REQUEST=(&(objectClass=groupOfUniqueNames)(uniqueMember={dn}))"
    - "LDAP_GROUP_ID_ATTRIBUTE=cn"
    - "SONARQUBE_JDBC_URL=jdbc:mysql://sonar-mysql:3306/${SONAR_MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true"
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: sonar

selenium-hub:
  container_name: selenium-hub
  restart: always
  image: selenium/hub:2.46.0
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "4444"
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: selenium-hub

selenium-node-chrome:
  container_name: selenium-node-chrome
  restart: always
  image: selenium/node-chrome:2.46.0
  net: ${CUSTOM_NETWORK_NAME}
  environment:
    SE_OPTS: "-nodeConfig /var/selenium-config/config-chrome.json"
    HUB_PORT_4444_TCP_ADDR: "selenium-hub"
    HUB_PORT_4444_TCP_PORT: "4444"
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: selenium-node-chrome

gerrit-mysql:
  container_name: gerrit-mysql
  restart: always
  image: mysql:5.6.25
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "3306"
  volumes:
    - gerrit_mysql_data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: "Password01"
    MYSQL_USER: ${GERRIT_MYSQL_USER}
    MYSQL_PASSWORD: ${GERRIT_MYSQL_PASSWORD}
    MYSQL_DATABASE: ${GERRIT_MYSQL_DATABASE}
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: gerrit-mysql

gerrit:
  container_name: gerrit
  restart: always
  image: accenture/adop-gerrit:0.1.0
  privileged: true
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "8080"
    - "29418"
  user: root
  volumes:
    - git_repos:/var/git/repos
    - gerrit_review_site:/var/gerrit/review_site
  environment:
    - "affinity:container==gerrit-mysql"
    - "REPO_PATH=/var/git/repos"
    - "WEBURL=http://${TARGET_HOST}/gerrit"
    - "DATABASE_TYPE=mysql"
    - "DB_HOSTNAME=gerrit-mysql"
    - "DB_PORT=3306"
    - "DB_NAME=${GERRIT_MYSQL_DATABASE}"
    - "DB_USER=${GERRIT_MYSQL_USER}"
    - "DB_PASSWORD=${GERRIT_MYSQL_PASSWORD}"
    - "AUTH_LOGOUTURL=http://${TARGET_HOST}/gerrit"
    - "AUTH_TYPE=LDAP"
    - "LDAP_SERVER=ldap:389"
    - "LDAP_ACCOUNTBASE=${LDAP_FULL_DOMAIN}"
    - "LDAP_ACCOUNTPATTERN=(cn=$${username})"
    - "LDAP_ACCOUNTFULLNAME=$${cn}"
    - "LDAP_ACCOUNTEMAILADDRESS=mail"
    - "LDAP_USERNAME=cn=admin,${LDAP_FULL_DOMAIN}"
    - "LDAP_PASSWORD=${LDAP_PWD}"
    - "LDAP_GROUPBASE=ou=groups,${LDAP_FULL_DOMAIN}"
    - "LDAP_GROUPPATTERN=(cn=$${groupname})"
    - "LDAP_GROUPMEMBERPATTERN=(uniqueMember=$${dn})"
    - "HTTPD_LISTENURL=proxy-http://0.0.0.0:8080/gerrit"
    - "USER_NAME=${GERRIT_USER_NAME}"
    - "USER_EMAIL=${GERRIT_USER_EMAIL}"
    - "DOWNLOAD_SCHEME=http"
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: gerrit

nexus:
  container_name: nexus
  restart: always
  image:  accenture/adop-nexus:0.1.0
  privileged: true
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "8081"
  environment:
    NEXUS_BASE_URL: "http://${TARGET_HOST}/nexus"
    LDAP_SEARCH_BASE: "${LDAP_FULL_DOMAIN}"
    LDAP_ENABLED: "true"
    LDAP_URL: "ldap"
    LDAP_BIND_DN: "cn=admin,${LDAP_FULL_DOMAIN}"
    LDAP_USER_PASSWORD_ATTRIBUTE: "userPassword"
    LDAP_USER_BASE_DN: "ou=people"
    LDAP_GROUP_BASE_DN: "ou=groups"
    LDAP_BIND_PASSWORD: ${LDAP_PWD}
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: nexus

elasticsearch:
  container_name: elasticsearch
  restart: always
  image: elasticsearch:2.1.1
  net: ${CUSTOM_NETWORK_NAME}
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
  volumes:
    - elasticsearch_data:/usr/share/elasticsearch/data
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: elasticsearch

logstash:
  container_name: logstash
  restart: always
  image: accenture/adop-logstash:0.1.0
  net: ${CUSTOM_NETWORK_NAME}
  environment:
    - "constraint:tier==public"
    - LS_HEAP_SIZE=1024m
  ports:
    - "12201:12201/udp"
    - "25826:25826/udp"
    - "5000:5000/tcp"
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: logstash

kibana:
  container_name: kibana
  restart: always
  image: kibana:4.3.1
  net: ${CUSTOM_NETWORK_NAME}
  command: kibana
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  ports:
    - "5601:5601"
  links:
    - elasticsearch
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.name: kibana
