name: Mesos
description: |
  Abstract resources away from machines, enabling
  fault-tolerant and elastic distributed systems
version: v1
category: Orchestration
maintainer: huangpeng <huangpeng1984101@163.com>
minimum_rancher_version: v1.0.0
