name: Onewire Collectors
description: |
  (Experimental) Onewire server, workers, and jobber
version: 0.1
category: onewire
maintainer: "Thomas Davis <tadavis@lbl.gov>"
minimum_rancher_version: v1.0.0
license: 
