.catalog:
  name: Chronos
  version: v1
  description: |
    Distributed, fault-tolerant cron replacement
  questions:
  - variable: VERSION
    label: Chronos Version
    description: Select the version of Chronos to run.
    required: true
    type: enum
    default: 2.4.0-centos-7
    options:
    - 2.4.0-centos-7
    - 2.4.0-ubuntu-14.04
  - variable: ZK_SERVICE
    description: Choose the Zookeeper service to use.
    label: Zookeeper Service
    required: true
    type: service
  # a stack type would be nice
  - variable: MESOS_SERVICE
    description: Choose the Mesos stack to use.
    label: Mesos Stack
    required: true
    type: service
  - variable: CHRONOS_HTTP_PORT
    description: Port to expose Chronos on.
    label: Chronos Port
    required: true
    type: int
    default: 8080
chronos:
  scale: 1
  health_check:
    port: ${CHRONOS_HTTP_PORT}
    interval: 3000
    unhealthy_threshold: 2
    healthy_threshold: 2
    request_line: '/'
    response_timeout: 2000
